"""Change platform_id to platform_ids JSON in Post model

Revision ID: 90851d3f84e8
Revises: 3bdd6ca0aba9
Create Date: 2025-09-25 15:22:40.417951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '90851d3f84e8'
down_revision: Union[str, Sequence[str], None] = '3bdd6ca0aba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('platform_ids', sa.JSON(), nullable=False))
    op.drop_constraint(op.f('posts_ibfk_2'), 'posts', type_='foreignkey')
    op.drop_column('posts', 'platform_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('platform_id', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('posts_ibfk_2'), 'posts', 'social_platforms', ['platform_id'], ['id'])
    op.drop_column('posts', 'platform_ids')
    # ### end Alembic commands ###
